name: nunchuk-linux-reproducible

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-linux-repro:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Determine Git tag
        id: vars
        run: echo "TAG=$(git describe --tags --abbrev=0 || echo '0.0.0')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --build-arg TAG=${{ env.TAG }} \
            -f reproducible-builds/Dockerfile.linux \
            -t nunchuk-repro .

      - name: Run reproducible build inside Docker
        run: |
          docker run --rm -e TAG=${{ env.TAG }} -v ${{ github.workspace }}:/project nunchuk-repro

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: nunchuk-linux-${{ env.TAG }}
          path: nunchuk-linux-v${{ env.TAG }}.AppImage
