name: nunchuk-linux-reproducible

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-linux-repro:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Determine Git tag
        run: |
          git fetch --all --tags --force
          git submodule sync --recursive
          git submodule update --init --recursive
          echo "LAST_COMMITID=$(git rev-parse HEAD)" >> $GITHUB_ENV
          # Get the latest tag based on the time it was tagged (taggerdate)
          LATEST_TAG=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
          CURRENT_COMMIT=$(git rev-parse HEAD)
          TAGGED_COMMIT=$(git rev-list -n 1 $LATEST_TAG)
          echo "Latest tag found: $LATEST_TAG (commit $TAGGED_COMMIT)"
          echo "Current commit: $CURRENT_COMMIT"
          echo "LATEST_VERSION=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --build-arg TAG=${{ env.TAG }} \
            -f reproducible-builds/Dockerfile.linux \
            -t nunchuk-repro .

      - name: Run reproducible build inside Docker
        run: |
          docker run --rm -e TAG=${{ env.TAG }} -v ${{ github.workspace }}:/project nunchuk-repro

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: nunchuk-linux-${{ env.TAG }}
          path: nunchuk-linux-v${{ env.TAG }}.AppImage
